version: '3'
services:
  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "virtualpets"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
