version: '3'
services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    user: 1000:1000
    environment:
      POSTGRES_DB: "virtualpets"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
