version: '3'
services:
  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql