version: '3.3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
# --init-file /data/application/init.sql
#    volumes:
#-     ./src/main/resources/schema.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"